### ISSUE TITLE
🚑 Check sur les numéros courts 🏣 

### ISSUE THREAD

**Issue by adriens** [opt-nc/phonenumber-validator#19]
# ❔ A propos

On check actuellement les nums : 

- fixes
- mobiles

mais pas les nums courts (créer une catégorie spéciale ?)

## 🚑 Numéros d'urgence

cf https://www.1012.nc/numeros-utiles/urgences

- 15
- 17
- 16
- 18
- 112 cf https://www.gouvernement.fr/risques/connaitre-les-numeros-d-urgence
- 114 (num. urgence pour personnes sourdes et malentendantes)
- 196 (secours en mer)

## 🏣  Numéro courts à 4️⃣ digits

[Num sur 4 : ](https://www.1012.nc/numeros-utiles/opt)

- 1000
- 1013
- 1010
- 1012
- 1000
- 1022
- 1016

[Numéros SOS](https://www.1012.nc/numeros-utiles/sos)

# 🎯 Objectifs

- [ ] Ajouter les types de numéro lorsqu'un de ces numéros est fourni en input (nouveaux ENUMs)
- [ ] `getter` pour récupérer les numéro courts via une entité dédiée (`num`, `description`)

# :bookmark: Ressource

[guide_des_essentiels_mes_demarches_en_un_clin_doeil](https://www.opt.nc/sites/serviciel/files/media/file/guide_des_essentiels_mes_demarches_en_un_clin_doeil.pdf)

[guide_des_essentiels_mes_demarches_en_un_clin_doeil.pdf](https://github.com/opt-nc/phonenumber-validator/files/9050659/guide_des_essentiels_mes_demarches_en_un_clin_doeil.pdf)

Doc officielle OPT :

**Comment by adriens** [comment]
Au moins répondre avec un type dédié

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/177447013-74eeb9f9-026e-40b6-8c85-b8ba1e4a2745.png)
![image](https://user-images.githubusercontent.com/5235127/177447140-d1d323de-46c6-42d9-826d-fc5f629a767f.png)

**Comment by adriens** [comment]
pas hésiter à compléter puis à utiliser https://github.com/opt-nc/numeros-utiles pour référentiel

**Comment by mbarre** [comment]
En parlant des numéro utiles, l'OPT a "injecté" la semaine dernière, les numéros utiles direct dans la SIM des téléphones. Christophe a eu une notif sur son téléphone pour savoir s'il acceptait que ces numéros soient ajoutés sur sa SIM. 

Tapez "samu", "police", "pompiers", les numéros sont enregistrés dans la SIM maintenant.

**Comment by adriens** [comment]
A voir si ç'est intéressant de les charger ici https://github.com/opt-nc/numeros-utiles

**Comment by mbarre** [comment]
Est-ce que cela te convient ? 

```shell
Numéro de téléphone formatté : +6871000
Numéro valide ? oui
Type de numéro : Services OPT-NC
Mobile ? : non
Fixe ? : non
Special ? : oui
Attribué ? : Service clientèle

Numéro de téléphone formatté : +68715
Numéro valide ? oui
Type de numéro : Urgence
Mobile ? : non
Fixe ? : non
Special ? : oui
Attribué ? : SAMU

Numéro de téléphone formatté : +687053030
Numéro valide ? oui
Type de numéro : SOS
Mobile ? : non
Fixe ? : non
Special ? : oui
Attribué ? : SOS Ecoute
```

**Comment by adriens** [comment]
carrément, oui :heavy_heart_exclamation:  Et que donne la vesion `json` :grey_question:

**Comment by mbarre** [comment]
ben la on est niveau sdk. J'attendais ton go pour voir coté api.

**Comment by adriens** [comment]
ben c'est top.

je voulais te poser la question hier : ce sera porté sur le JBang du coup ?

**Comment by adriens** [comment]
C'est top car on va avoir en même temps sms-cli et le validtaeur, c'est vraiment très très bon tt ça

**Comment by mbarre** [comment]
> je voulais te poser la question hier : ce sera porté sur le cli JBang du coup ?

https://github.com/opt-nc/jbang-catalog/issues/4

**Comment by adriens** [comment]
U :arrow_right: :1st_place_medal:
