### ISSUE TITLE
📝  Simplification README : exemple de code (mvn exec:java)

### ISSUE THREAD

**Issue by adriens** [opt-nc/phonenumber-validator#24]
Au lieu de `java -jar`, utiliser [`exec-maven-plugin`](https://www.mojohaus.org/exec-maven-plugin/usage.html) : 

La doc passera de : 

```shell
mvn clean package
java -jar target/phonenumber-validator-1.0.0.jar
```

à : 

```shell
mvn exec:java
```

**Comment by adriens** [comment]
t'as testé ❔

**Comment by mbarre** [comment]
tester c'est douter...

**Comment by mbarre** [comment]
je ne doute jamais de tes propositions :smile:

**Comment by adriens** [comment]
Mais je vois pas la doc sur `README` : 

![image](https://user-images.githubusercontent.com/5235127/177932838-37d15dbf-7ab5-47a1-870d-1a60fa794fd4.png)

**Comment by adriens** [comment]
... ou alors j'ai de la :hankey: dans les :eyes: :grey_question:

**Comment by adriens** [comment]
```shell
gh repo clone opt-nc/phonenumber-validator
cd phonenumber-validator/
mvn exec:java
```

:point_down: 

![image](https://user-images.githubusercontent.com/5235127/177933947-579194a6-a925-4613-9900-ad4b5cc0420c.png)

**Comment by adriens** [comment]
Même sur https://github.com/opt-nc/phonenumber-validator/tree/docs/exemple_code ça coince : 

```
git switch docs/exemple_code
mvn exec:java
```

:point_down: 

![image](https://user-images.githubusercontent.com/5235127/177934584-7b68ae11-5adc-4efa-aac8-512e48478f96.png)

**Comment by adriens** [comment]
Manque le pointeur vers le `Main` :nerd_face:

**Comment by mbarre** [comment]
Comme aurait dit Ronny "ca marche sur mon poste"
Bizarre que ca ne fonctionne pas chez toi, tout est sur la branche pourtant

![image](https://user-images.githubusercontent.com/1823161/178162254-1667cc26-ed71-4d82-a907-f5970a33b474.png)

**Comment by adriens** [comment]
T'as essayé en cloant sur un env vierge ?

**Comment by adriens** [comment]
Scénario de test complet : 

```shell
cd /tmp
rm -rf phonenumber-validator
gh repo clone opt-nc/phonenumber-validator
cd phonenumber-validator
mvn exec:java
cd ..
rm -rf phonenumber-validator
```

**Comment by mbarre** [comment]
Ok, en faisant un `mvn clean` avant, j'ai la même erreur que toi.

En fait la "vraie" commande c'est : `mvn compile exec:java`

Merci pour le test "from scratch" que j'avais zappé :smile_cat:

**Comment by adriens** [comment]
ca coince toujours sur mon :keyboard: 

```
cd /tmp
rm -rf phonenumber-validator
gh repo clone opt-nc/phonenumber-validator
cd phonenumber-validator
mvn compile exec:java
cd ..
rm -rf phonenumber-validator
```

![image](https://user-images.githubusercontent.com/5235127/178168216-8e2fca0c-2f9a-4967-8349-abb1c5f17f2c.png)


... si je `clean package` je vais un peu plus loin... mais ça coince toujours : 

```
mvn clean package
mvn exec:java
```

idem avec 

```
mvn clean
mvn compile exec:java
```

![image](https://user-images.githubusercontent.com/5235127/178168471-4ed8db5f-5f27-4134-b7ce-b4b8b0809307.png)

**Comment by mbarre** [comment]
Je viens de comprendre, tu es sur la branche `main`. Le code est encore sur la branche `develop`

**Comment by adriens** [comment]
Tu veux pas laisser ouvert tant que c pas mergé stp ? Comme ça je saurait quand tester please
