### ISSUE TITLE
🧽  Formattage numero de telephone quelque soit le format d'entree (suppression des caracteres alpha, etc..) 

### ISSUE THREAD

**Issue by mbarre** [opt-nc/phonenumber-validator#28]

**Comment by adriens** [comment]
Yes, cette idée est vraiment top, bien joué de pas se résigner 💪

**Comment by adriens** [comment]
Issue priorisée en 1️⃣  sur le [Kanban](https://github.com/opt-nc/phonenumber-validator/projects/1)

**Comment by mbarre** [comment]
En fait, libphonenumber fait toujours le boulot, c'etait juste une mauvaise utilisation de lib de ma part. Je m'en suis rendue compte ce matin.

**Comment by adriens** [comment]
... et autant de code à pas tester ;-p
