### ISSUE TITLE
:bulb:  ReleaseNote > Amélioration section deps upgrade

### ISSUE THREAD

**Issue by adriens** [opt-nc/phonenumber-validator#60]
# :grey_question: Contexte

Actuellement les uprgades de deps sont flaggéés comme des bugs, c'est pas exact (la plupart du temps :sweat_smile: )

![image](https://user-images.githubusercontent.com/5235127/181104731-38d53dd1-c844-41af-bcbb-60044624d813.png)

# :dart: Actions

:bulb: Créer une section dédiée aux deps upgrades :grey_question:

**Comment by mbarre** [comment]
Normalement en commit semantique, on utilise le prefixe `chore` ou `build` pour l'upgrade de dépendance, mais cela ne provoquera pas de nouvelle release.

**Comment by adriens** [comment]
Ah 💩

**Comment by adriens** [comment]
⚡
