### ISSUE TITLE
🐦 Annoncer les releases via Twitter 🔊 

### ISSUE THREAD

**Issue by adriens** [opt-nc/phonenumber-validator#7]
Via :bird:  [`optnc_dev`](https://twitter.com/optnc_dev)

**Comment by adriens** [comment]
Voir si on release avec JReleaser ou juste une GH Action

**Comment by adriens** [comment]
la release note est vraiment super clean :medal_sports: 

![image](https://user-images.githubusercontent.com/5235127/180743727-31d9e377-0ed3-4acf-b0e4-85afaa9010af.png)

**Comment by mbarre** [comment]
Yep, par contre, le workflow d'annonce sur twitter ne s'est pas lancé, car le token utilisé ne permet pas lancer l'event `release published`

**Comment by mbarre** [comment]
Je regarde cote JReleaser, mais on reste sur la même problèmatique : c'est semantic-release qui déclenche la release avec un token qui n'a pas les acces suffisant donc difficile de déclencher JReleaser pour l'annonce.

Ensuite, tout gérer cote JReleaser nous oblige a déclencher nous même les releases. Plus de release automatique en fonction des commits semantiques lorsqu'on push sur la branche `main`

**Comment by mbarre** [comment]
En fait, il y a une derniere piste a laquelle je n'avais pas pensé et pourtant ca me parait evident....
Je vais essayer de lancer l'action d'annonce de JReleaser avec le plugin maven et semantic-release (vu qu'on peut lancer des commandes maven.)

**Comment by mbarre** [comment]
Ca avance mais depuis la CI c'est un peu compliquer de débuguer.
En lancant depuis mon poste j'arrive a cette erreur :

```shell
[DEBUG] Request: 
[DEBUG] POST https://api.twitter.com/1.1/statuses/update.json
[DEBUG] OAuth base string: POST&https%3A%2F%2Fapi.twitter.com%2F1.1%2Fstatuses%2Fupdate.json&include_entities%3Dtrue%26include_ext_alt_text%3Dtrue%26oauth_consumer_key%3D8CP9mMzrhoXEmF3mLEEPMXESd%26oauth_nonce%3D291499047%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1658871887%26oauth_token%3D1544062610840367104-yyAbFR9jXCGLM48HYGijkD1mqZKN17%26oauth_version%3D1.0%26status%3D%25F0%259F%2593%25A2%2520We%2527ve%2520just%2520released%2520phonenumber-validator%2520v1.2.3%2521%2520%25F0%259F%259A%2580%2520%255Cn%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%25F0%259F%2591%2589%2520https%253A%252F%252Fgithub.com%252Fopt-nc%252Fphonenumber-validator%252Freleases%252Ftag%252Fv1.2.3%2520%255Cn%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2523NouvellCaledonie%2520%2523opensource%2520%2523openinnovation%2520%2523techforgood%26tweet_mode%3Dextended
[DEBUG] OAuth signature: zvFxpWFYzOerC47aju2QwUsQd7o=
[DEBUG] Authorization: **********************************************************************************************************************************************************************************************************************************************************************************
[DEBUG] X-Twitter-Client-Version: 4.0.7
[DEBUG] X-Twitter-Client-URL: http://twitter4j.org/en/twitter4j-4.0.7.xml
[DEBUG] X-Twitter-Client: Twitter4J
[DEBUG] User-Agent: twitter4j http://twitter4j.org/ /4.0.7
[DEBUG] Accept-Encoding: gzip
[DEBUG] Post Params: status=%F0%9F%93%A2%20We%27ve%20just%20released%20phonenumber-validator%20v1.2.3%21%20%F0%9F%9A%80%20%5Cn%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%F0%9F%91%89%20https%3A%2F%2Fgithub.com%2Fopt-nc%2Fphonenumber-validator%2Freleases%2Ftag%2Fv1.2.3%20%5Cn%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23NouvellCaledonie%20%23opensource%20%23openinnovation%20%23techforgood&include_entities=true&include_ext_alt_text=true&tweet_mode=extended
[DEBUG] Response: 
[DEBUG] date: Tue, 26 Jul 2022 21:44:49 GMT
[DEBUG] HTTP/1.1 403 Forbidden
[DEBUG] server: tsa_l
[DEBUG] content-length: 270
[DEBUG] x-response-time: 153
[DEBUG] x-connection-hash: 88df84d98c20e941610c615dc371e0c9f737f54b946d69ed1aaa5354abd9c33c
[DEBUG] content-encoding: gzip
[DEBUG] content-type: application/json;charset=utf-8
[DEBUG] cache-control: no-cache, no-store, max-age=0
[DEBUG] {"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve","code":453}]}

[WARNING]   [twitter] org.jreleaser.sdk.twitter.TwitterException: Twitter operation failed
```
Pour acceder a l'api standard v1.1 qui permet de poster, il nous faut le niveau d'accès `Elevated` à priori tu dois pouvoir le faire, depuis le compte developpeur.

Voici la doc :
https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve
https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api



![Image](https://user-images.githubusercontent.com/1823161/181120509-32294910-fe7c-4609-a626-9907a55de3b2.png)

**Comment by adriens** [comment]
OULA, ok, rien vu de tel.
On va se faire une session dédiée je pense.
Evnoie moi une invitation et on fixe ça.

**Comment by mbarre** [comment]
atelier prevu vendredi

**Comment by mbarre** [comment]
Demande faite auprès de twitter vendredi pour un changement de privilege et d'acces.
En attente de la reponse.

**Comment by adriens** [comment]
Oui... pour l'instant j'ai rien du tout comme retour...
:pause_button:

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/183775116-f4330a71-10ce-427d-9ea3-10eeac990582.png)

**Comment by mbarre** [comment]
🎉 

![Image](https://user-images.githubusercontent.com/1823161/189266158-f9561b42-7748-4716-b6d8-1f29675e4615.png)

**Comment by adriens** [comment]
yes @mbarre :clap: :muscle: :rocket: :star_struck: 
![image](https://user-images.githubusercontent.com/5235127/189303922-53a11c81-2761-49e1-93d7-411f6a408804.png)

**Comment by adriens** [comment]
https://twitter.com/optnc_dev/status/1568079026442620928

![image](https://user-images.githubusercontent.com/5235127/189450156-7d33f5e8-414e-45f7-a6b1-c7faa795c693.png)
