### ISSUE TITLE
:memo: Article DEV.to dédié au script sur catalogue JBang! :nerd_face: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/phonenumber-validator#73]
fait suite à #10

**Comment by adriens** [comment]
:point_right:  Pour info @mbarre

**Comment by adriens** [comment]
Premier draft produit.
:pause_button: avant relecture prochaine et release prochaine :rocket:

**Comment by mbarre** [comment]
yep super. Rien à a ajouter pour ma part.

**Comment by adriens** [comment]
Je l'envoie jeudi :newspaper_roll:

**Comment by adriens** [comment]
cf https://github.com/opt-nc/phonenumber-validator/pull/74

https://dev.to/optnc/validate-new-caledonia-phone-numbers-from-cli-2bc3

**Comment by adriens** [comment]
https://twitter.com/rastadidi/status/1570169993291272193

**Comment by adriens** [comment]
[linkedIn ](https://www.linkedin.com/posts/adrien-sales_validate-new-caledonia-phone-numbers-from-activity-6975938308124090368-Eg1D?utm_source=share&utm_medium=member_desktop): 

![image](https://user-images.githubusercontent.com/5235127/190271790-857185f9-dedd-47f2-940b-96825d5a361c.png)
